name: rio-color test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt -r requirements-dev.txt

      - name: Install module
        run: python -m pip install -e .

      - name: Run tests
        run: |
          pre-commit run --all-files
          python -m pytest --cov rio_color --cov-report term-missing
